// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PasswordMatchController from "./password_match_controller"
application.register("password-match", PasswordMatchController)

import PasswordStrengthController from "./password_strength_controller"
application.register("password-strength", PasswordStrengthController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PricingController from "./pricing_controller"
application.register("pricing", PricingController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TiptapController from "./tiptap_controller"
application.register("tiptap", TiptapController)

import ViewToggleController from "./view_toggle_controller"
application.register("view-toggle", ViewToggleController)
