services:
  - type: web
    name: specline
    env: docker
    plan: free
    healthCheckPath: /up
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_LEVEL
        value: info
      - key: RAILS_MAX_THREADS
        value: "5"
      - key: APP_HOST
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ACTIVE_STORAGE_SERVICE
        value: local
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: SMTP_ADDRESS
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_PORT
        value: "587"
